# Generated by Django 5.2.12 on 2026-04-10 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_livro_editora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(blank=True, related_name='livros', to='core.autor'),
        ),
    ]
